name: Docker

on:
  workflow_call: # O gatilho deste workflow vai ser a chamada em outro workflow(go.yml)
  
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: lucasnrdrigues
        password: ${{ secrets.PASSWORD_DOCKER_HUB }} # Precisa criar esta variável no secrets
