name: Go

on:
  push:
    branches: [ '*' ] # O asterístico indica que é qualquer branch
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }} # Rodando os testes em 2 so diferentes, definidos abaixo em "os" em matrix
    # Adicionando variáveis de ambiente, devemos por dentro de um job
    env:
      HOST: localhost
      PORT: 5432
      USER: user
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker compose build
      
    - name: Create-DB
      # run: docker-compose up -d -> comando descontinuado, não usa mais com o hífen
      run: docker compose up -d

    - name: Test
      run: go test -v main_test.go 
      
  build:
    needs: test
    runs-on: ${{ matrix.os }} # Rodando o build também nos OS definidos acima
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
